---
title: "sdsbrowser"
subtitle: Shiny Application for visualisation and analysis of SDS stone artefact data
date: "04/2019"
institute: Institute of Pre- and Protohistoric Archaeology, Kiel University
fontsize: 9pt
output:
  beamer_presentation:
    includes: 
      in_header: preamble.tex
    keep_tex: true
fig_caption: yes
editor_options: 
  chunk_output_type: console
---

```{r, echo = FALSE}
# https://stackoverflow.com/questions/25646333/code-chunk-font-size-in-rmarkdown-with-knitr-and-latex
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## TOC

\huge

- Data preservation and sharing in Archaeology

- The SDS System
  - The Idea
  - The Implementation
  
- Making SDS data accessible
  - R & Shiny
  - sdsanalysis
  - sdsbrowser

- Lessons for the future

# Data preservation and sharing in Archaeology

## Context data preservation and sharing

\underline{Problems:}

- Archaeology produces **Bad Data** (pretty shitty Big Data)
  - Volume -- low end of the spectrum
  - Variety -- a lot! And a significant **lack of metadata**
  - (Velocity)
  - Veracity -- highly different data quality
- Lack of data (and code) sharing
- Lack of long term storing strategies

\underline{Postive pressure:}

- Funding and Journal requirements 
- Open Science and Reproducible Research Movement

\underline{Tools and enabling features:}

- Data Storage Providers (e.g. ADS)
- Data Journals
- Licensing 
- new **Software, Platforms and Frameworks**

# The SDS System 

## SDS -- The Idea

## SDS -- The Implementation

# Making SDS data accessible

## sdsanalysis -- Backend

## sdsbrowser -- Webapp

# Lessons for the future

## Lessons
